language: node_js
node_js:
- '10'
cache: npm
deploy:
  provider: npm
  email: oss@realglobe.jp
  api_key:
    secure: Hnb+JySyvr1MLu3ATZYj1JUMkTB91UXIQnnEIRUnb40gqh672xuPuhCXYCy1lvfz4Qzx8v6B0/FCkPr+7SfoksvvSqK6mrFbs13kY5dsP0LrWGDf2NKCd6aru774c8BUlunichdfu9YlbBKTDP15C9F0SuEVT/6YHMMxE1K3j4/mUbjlJ2WHHURZev1zAkjL9G+OjS/8qUIcPPrvmIdzinWU8d7O+kT4qKPY3OCGdMoCjoXHqU+uM1haaPSC7D7irqqSfaNy10pZPoqhcmbjD6nXt328fn0zgFbLIekUg8awEM6UcKMACFnjmDs2h3+hFFCWmcMt3qZWvEiu4fN5mVoqHPmIxwrhZL+pGvc5hwXsMtsbaMn4zR8CF9LzcjkhIIBXzG30gqsNGZd90Aft9yU0+xcYTGlflzoB3w1KZrZJkjrCCh443cqfHUj8S53n7WtYbyDeLUDx6dnVVtSNMGTN45UudKKZ9GUEFmao8We42HLFaHRkEU4JuEiaz4aYChUZtg70PBy9f93DGplfkctBC1rbIvfOxoPa5OvgqE+SIzQ4hDLUPevsfope0Z6Jdw57ISXRceWDAbuZ7WqZO2A8+UyenPjQM7mq2tnerIAk++p0La7IhHJ1Op4L+/dNLLXPd+o/kKtVIFbIQeibu+YagMjkHl7Y+zokbJwasnc=
  on:
    repo: realglobe-Inc/v-rpc
    branch: master
  skip_cleanup: true
